GuohuaZhang.App.TaskManagementSystem/GuohuaZhang.App.TaskManagementSystemMVC/Controllers/TasksController.cs
using ApplicationCore.Models;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GuohuaZhang.App.TaskManagementSystemMVC.Controllers
{
    public class TasksController : Controller
    {
        private readonly ITasksService _tasksService;

        public TasksController(ITasksService tasksService)
        {
            _tasksService = tasksService;
        }

        public async Task<IActionResult> Details(int id)
        {
            var task = await _tasksService.GetTasksById(id);
            return View(task);
        }

        public async Task<IActionResult> NewTask()
        {
               
            return View();
        }

        public async Task<IActionResult> CreateNewTask(TaskRequestModel taskRequestModel)
        {
            if (!ModelState.IsValid)
            {
                //save to DB
                return View();
            }
            var taskResponse = await _tasksService.AddTask(taskRequestModel);

            return RedirectToAction("Index","Home");
        }
    }
}

GuohuaZhang.App.TaskManagementSystem/GuohuaZhang.App.TaskManagementSystemMVC/Controllers/TasksHistoryController.cs
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GuohuaZhang.App.TaskManagementSystemMVC.Controllers
{
    public class TasksHistoryController : Controller
    {
        private readonly ITasksHistoryService _tasksHistoryService;
        public TasksHistoryController(ITasksHistoryService tasksHistoryService)
        {
            _tasksHistoryService = tasksHistoryService;

        }
        public async Task<IActionResult> ShowHistory()
            
        {
            var taskHistory = await _tasksHistoryService.GetRecentTask();
            return View(taskHistory);
        }

        public async Task<IActionResult> Details(int id)
        {
            var task = await _tasksHistoryService.GetTasksHistoryById(id);
            return View(task);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _tasksHistoryService.DeleteTask(id);
        
            
            return RedirectToAction("ShowHistory");
        }
    }
}

GuohuaZhang.App.TaskManagementSystem/GuohuaZhang.App.TaskManagementSystemMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]-TaskManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskManagementSystem</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <partial name="_NewTask" />
                    </ul>
                </div>
            </div>
            <div class="navbar-collapse collapse w-100 order-3">
                <form class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
     
            
            <partial name="_LoginPartial" />
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - GuohuaZhang.App.TaskManagementSystemMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GuohuaZhang.App.TaskManagementSystem/GuohuaZhang.App.TaskManagementSystemMVC/Views/Shared/_NewTask.cshtml
@using ApplicationCore.ServiceInterfaces
@inject ITasksService _tasksService
@inject ICurrentUser _currentService

 
<button class="btn btn-outline-primary my-2 my-sm-0" type="submit">

        <a  asp-controller="Tasks" asp-action="NewTask" asp-route-id="@_currentService.UserId">
            New Task
        </a>
</button>

GuohuaZhang.App.TaskManagementSystem/GuohuaZhang.App.TaskManagementSystemMVC/Views/Shared/_TaskDetailCard.cshtml
@model ApplicationCore.Models.TasksResponseModel

<tr>
    <td></td>
</tr>

GuohuaZhang.App.TaskManagementSystem/GuohuaZhang.App.TaskManagementSystemMVC/Views/Shared/_TasksCard.cshtml
@model ApplicationCore.Models.TasksResponseModel

<div class="card mb-4 shadow bg-light">
    <a asp-controller="Tasks" asp-action="Details" asp-route-id="@Model.Id">

        <h1>Task ID: @Model.Id</h1>
        <h1>Task UserID: @Model.userid</h1>
        <h1>Task Title: @Model.Title</h1>
@*        <p>@Model.Description</p>
        <p>@Model.DueDate</p>
        <p>@Model.Completed</p>
        <p>@Model.Remarks</p>*@
    </a>
</div>

GuohuaZhang.App.TaskManagementSystem/GuohuaZhang.App.TaskManagementSystemMVC/Views/Shared/_TasksHistoryCard.cshtml
@model ApplicationCore.Models.TasksHistoryCardResponseModel

<div class="card mb-2 shadow bg-light">

    <a asp-controller="TasksHistory" asp-action="Details" asp-route-id="@Model.TaskId">
        <p>UserId       : @Model.UserId</p>
        <p>Title        : @Model.Title</p>
        <p>Description  : @Model.Description</p>
        <p>DueDate      : @Model.DueDate</p>
        <p>Completed    : @Model.Completed</p>
        <p>Remarks      : @Model.Remarks</p>
    </a>
</div>